label_names = data.frame(name = DF$name,
                         label_name = NA)

label_names$label_name[label_names$name == 1] <- expression(italic(alpha["ϵ"]))
label_names$label_name[label_names$name == "2"] = expression(italic(beta["ϵ"]))
label_names$label_name[label_names$name == "3"] = expression(italic("U"["ϵ"]))
label_names$label_name[label_names$name == "4"] = expression(italic("h"))
label_names$label_name[label_names$name == "5"] = expression(italic("v"))
label_names$label_name[label_names$name == "6"] = expression(italic("C"))
label_names$label_name[label_names$name == "7"] = expression(italic("D"["frac"]))
label_names$label_name[label_names$name == "8"] = expression(italic("K"["D"]))
label_names$label_name[label_names$name == "9"] = expression(italic("z"))
label_names$label_name[label_names$name == "10"] = expression(italic("b"))
label_names$label_name[label_names$name == "11"] = expression(italic("m"))
label_names$label_name[label_names$name == "12"] = expression(italic(alpha["dig"]))
label_names$label_name[label_names$name == "13"] = expression(italic(beta["dig"]))
label_names$label_name[label_names$name == "14"] = expression(italic(delta^"*"))
label_names$label_name[label_names$name == "15"] = expression(italic(alpha["gut"]))
label_names$label_name[label_names$name == "16"] = expression(italic(beta["gut"]))
label_names$label_name[label_names$name == "17"] = expression(italic(alpha["met"]))
label_names$label_name[label_names$name == "18"] = expression(italic(beta["met"]))
label_names$label_name[label_names$name == "19"] = expression(italic("Q"[10]))
label_names$label_name[label_names$name == "20"] = expression(italic("F"))
label_names$label_name[label_names$name == "21"] = expression(italic(zeta["SDA"]))
label_names$label_name[label_names$name == "22"] = expression(italic(alpha["alloc"]))
label_names$label_name[label_names$name == "23"] = expression(italic(beta["alloc"]))
label_names$label_name[label_names$name == "24"] = expression(italic(delta["S"]))
label_names$label_name[label_names$name == "25"] = expression(italic(delta["R"]))
label_names$label_name[label_names$name == "26"] = expression(italic(alpha["dry"]))
label_names$label_name[label_names$name == "27"] = expression(italic(beta["dry"]))
label_names$label_name[label_names$name == "28"] = expression(italic(omega["SDW"]))
label_names$label_name[label_names$name == "29"] = expression(italic(omega["RDW"]))




DF = merge(DF, label_names, by = "name", sort = "FALSE")